language: java
notifications:
  email: false
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep  -v
  '\[')
deploy:
  provider: releases
  api_key:
    secure: ozYeiUvEtFuQE2DHXIyNUoHc66TBmB97RSfCbrppYrbblUutULyk4qCUjhMldWUmvw2mM5BfTcD0s8HO1ayIghaiaWjyQAbDPrQZ7ezdtqrHWar0n3pF4TUojg2CdkDYusrWCPTh/ndMqVE9+GmDlcEumdMFaqxwdLYeSI6mSy38UBFQ+gFtXi7J5wfaK7gULcZzLqoBRSjrCGagWrUBdZ6YvLUTsjFwOd0kIAVuv5JwGkUzE7OIQhu054uk+o/fqWbWP2b0FieHfih+dHyIYFD8jh+DphWCfm2JzA1lPf785jlCOzEdKT6aORnxBwOeh/6UxOTLzRQ6vmPL9ou8M3lUtJh0cTDNZkGbXHD0x7e7HOhSnzMBPfxsOeE3Sxy1uRUF/43j53wqNRGNTFb06CA9+HPxnZUXOjfpeJHy00qmxFG3NzTnEqEfcEc7Ulcy59rnYvgtNkuiA8HeUsgpGwqoxKyKpi2zqfwI0DUyNEHoyKjeemrAZUg9/1DlXqQ7r/YBOVgERI2P9d908WkaWDond7hc18FOTYpVUeFxbAcby8hjlVnvC2GOlwHlRdTERq1UOaP/iEwSPLYc7Z1EmxgQBOEczytnO2gYXyXe3exyeOfiWhprHwU2VmjyBmkxtqHe7GvRutXdlZBbWBx5LzoX9VjyNZnTdNPH6pif7sU=
  file:
  - easyms-basic-starter/target/easyms-basic-starter-$project_version.jar
  - easyms-rest-starter/target/easyms-rest-starter-$project_version.jar
  - easyms-sample-ms/target/easyms-sample-ms-$project_version.jar
  - easyms-secured-rest-starter/target/easyms-secured-rest-starter-$project_version.jar
  - easyms-secured-sample-ms/target/easyms-secured-sample-ms-$project_version.jar
  skip_cleanup: true
  on:
    repo: SahloulIheb/easyms-sdk
  name: easyms-$project_version
