language: java
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  api_key:
    secure: EXrfAnIgCkt760ybZ7v3du54u0ewwalFgcRiVIpOLp0sHkKxuqJFby3hpPOYZP+M3p62ei1zwMFjxxZumpMQhCVA6as9nqpIapXdEQwGddS6u1ZEVKiB+O8F4ItT2cXU38wY3ASi6EvFwPaHtzZL6YxAOjF4lRLHCXMUNCRGd8lKmca8w14YLYoGNtuM2QwZZVuzJaEun0bNFMGk1jk3Ek8H+dCaQGEgGpQA69PZMPnUc5AYxru1TL/EQvljSAKKa9ChrR0wnv4n3sl9J8tykxplU/KOF4VjYMhQGy9XH/++EMgwoCsL8U1KyMScrdtHDMePj7+VPDc0N/UIcNRmljKE63k9daoR2mIczNSdvnkNbWrkxq1RaukuCff38zUROByRXZuPxCqkgtK4bzY59VlT8BRoc/GLmYKEDTswBTL076f/Jayb5xMhuYQyhEMPBA86qbgUwxplqbF4cjYLIDUHjmqv8uinDq6ej7Shf3KsI91VAN4JW/2fXDr8SZGTE2A4tZAxual7FXMMz1UrirGz+Hc1HDHteUZOHfoq66Sk07/fNxQCPxtQnmjioOmJYnwyOl1qaEhqxvlLW5bUoepAMWNASe572K0YyA9WGNjeod1qwQJbVnzL3inHK0lV5yrPze7/szj+iyU14JLFf0O6bDvUMFID1ozjH0feKoU=
  file:
    - easyms-basic-starter/target/easyms-basic-starter-$project_version.jar
    - easyms-rest-starter/target/easyms-rest-starter-$project_version.jar
    - easyms-sample-ms/target/easyms-sample-ms-$project_version.jar
    - easyms-secured-rest-starter/target/easyms-secured-rest-starter-$project_version.jar
    - easyms-secured-sample-ms/target/easyms-secured-sample-ms-$project_version.jar

  skip_cleanup: true
  on:
    repo: SahloulIheb/easyms-sdk
  name: $project_version