language: java
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep  -v
  '\[')
deploy:
  provider: releases
  api_key:
    secure: GIhNtcEZ63zpa3Ldb+xqcov2ke+xn3vd/fWjEo1Nou4eOU+GOyMz1FT1Tjl30lvDm832PbyhF4gAUJZctr98KIgT+vqZmTpz5KfGnl/DtfVwts66nEMIF3O3GQMpPAlfKvKDY1jnNRfPmbUKiZUx9Rk2xo/Vjl/s9ek3TKqjQw6Kx94anobUro4R8zGq5HhqY+UZZ7x7wvQsCw77ngrwU5+kTvkdZC7yt9Lh8Gk5Mfpsd79FkeGUGQioZGNUJhgUqfwfihed5dmdO7f5YeeKp9IJYxMHH2ScNKGEXjmx9JMSTOnn35w6afrnP7RfNrX3rNn3swJ9nLs3DfyzHYH49laGcjvug0zPV5pJyKycTKJB33FqowuYZ/HPL/QupIhMeYoTQcYisuI1FnoNK/1qvW+WFxYQ7bmehXsOckQMVkVferiUD3T9JiHy1MfvwxuVCadsue2AVDrq97fUdaRUhTrroaxlK7XQIShALafBrRGD+y2FivftQ48CKWnVAjyEqogEcNU2v9hkFbSyihuwVAJxElonAIbhjF1YJnEaIMPUpziicq2WGyAxhUVXA7Oto9B1mAfOncDtlw3xiSKxtreItPoPABli6KYft+ASnKuwfLEjf/rW9BQ31b92zujeqknzvDbqwQB5870uD9AMLW7EBrqYIS1vivifevPsB1A=
  file:
    -easyms-basic-starter/target/easyms-basic-starter-$project_version.jar
    - easyms-rest-starter/target/easyms-rest-starter-$project_version.jar
    - easyms-sample-ms/target/easyms-sample-ms-$project_version.jar
    - easyms-secured-rest-starter/target/easyms-secured-rest-starter-$project_version.jar
    - easyms-secured-sample-ms/target/easyms-secured-sample-ms-$project_version.jar
  skip_cleanup: true
  on:
    repo: SahloulIheb/easyms-sdk
  name: easyms-$project_version